config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :food_taxonomies, only: %i[index]
    resources :time_zones, only: %i[index]
    resources :shift_event_occurrences, only: %i[index show] do
      resources :task_logs, only: %i[create]
      resource :shift_event_note, path: "note", only: %i[show create]
    end
    resources :users, only: %i[show update] do
      resources :absences, only: %i[index create update destroy]
      resources :alerts, only: %i[index]
      resources :shift_event_occurrences, only: %i[index] do
        post "/pickup", to: "pickup#pickup", as: :pickup_shift
      end
      get "shift_event_occurrences/pickup", to: "pickup#index", as: :list_pickup_shifts
    end
    resources :organizations do
      resources :shifts
    end
  end

  resource :current_user, only: %i[edit update]
  resources :users, only: %i[show update]
  resources :organizations do
    resources :shifts
    resources :sites
    resources :shift_event_occurrences
    resources :users, only: %i[index show]
    resources :receipts, only: %i[new create]
    resources :csv_exporters, only: %i[create index]
  end

  resources :shift_event_occurrences, only: %i[show edit update destroy] do
    resources :task_logs, only: %i[create]
  end

  devise_for :users, path: "auth", path_names: { sign_in: "login", sign_out: "logout" }, skip: [:invitation]
  devise_scope :user do
    get "/organizations/:id/invite", to: "organization_invitations#new", as: :new_user_invitation
    post "/organizations/:id/invite", to: "organization_invitations#create", as: :create_user_invitation
    post "/organizations/:organization_id/users/:id/resend_invite", to: "users#resend_invite",
      as: :resend_user_invitation
    get "/auth/invitation/accept", to: "organization_invitations#edit", as: :accept_user_invitation
    put "/auth/invitation", to: "organization_invitations#update", as: :user_invitation
  end

  get "/rrule", to: "rrule#index"

  root to: "pages#root"

  match "*path", to: "pages#volunteer_root", via: :all
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  admin_notes         :text
#  created_at          :datetime         not null
#  detailed_hours_json :text
#  id                  :bigint           not null, primary key
#  instructions        :string           default(""), not null
#  lat                 :decimal(, )
#  lng                 :decimal(, )
#  name                :string           not null
#  organization_id     :bigint
#  receipt_key         :string
#  robot_location_id   :integer
#  siteable_id         :bigint
#  siteable_type       :string
#  updated_at          :datetime         not null
#  website             :string
#
# Indexes
#
#  index_sites_on_organization_id                (organization_id)
#  index_sites_on_organization_id_and_name       (organization_id,name) UNIQUE
#  index_sites_on_robot_location_id              (robot_location_id)
#  index_sites_on_siteable_id_and_siteable_type  (siteable_id,siteable_type)
#
require "csv"
class Site < ApplicationRecord
  TYPES = %w[Donor Recipient Hub]

  delegated_type :siteable, types: TYPES, dependent: :destroy

  belongs_to :organization
  has_many :tasks, dependent: :destroy
  has_one :address, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :address, allow_destroy: true

  validates :name, presence: true, uniqueness: { scope: :organization_id }
  validates_associated :siteable

  before_create :build_task_attributes

  def self.siteable_types
    TYPES
  end

  def build_task_attributes
    return if siteable.blank?

    tasks.build(siteable.build_task_attributes)
  end
end

app/controllers/api/shift_event_occurrences_controller.rb
module Api
  class ShiftEventOccurrencesController < ApiController
    before_action :authenticate_user!

    include ShiftEventOccurrenceLoader
    before_action :load_occurrence, only: %i[show]
    before_action :authorize_resources

    def index
      skip_authorization

      range = (1.week.ago)..(1.month.from_now)
      @occurrences = EventsService.all_user_occurrences current_user, range
    end

    def show
      @food_taxonomies = FoodTaxonomy.all
    end

    private

    def authorize_resources
      authorize @occurrence.event if @occurrence
    end
  end
end

app/controllers/shift_event_occurrences_controller.rb
class ShiftEventOccurrencesController < ApplicationController
  before_action :authenticate_user!

  include ShiftEventOccurrenceLoader
  before_action :load_occurrence, only: %i[show edit update destroy]
  before_action :authorize_resources

  def index
    if params[:user_id] == "me"
      skip_authorization

      range = (Time.zone.now.midnight)..(1.week.from_now.midnight)
      @occurrences = EventsService.all_user_occurrences current_user, range
    else
      @occurrences = []
    end
  end

  def show
    @food_taxonomies = FoodTaxonomy.all
  end

  def edit
    @tasks = if edit_tasks?
               Task.find(edit_shift_event_params[:task_ids].compact_blank)
             else
               @occurrence.shift_event.tasks
             end

    @available_tasks = Task
      .joins(:site)
      .where(sites: { organization_id: @occurrence.ownable.id })
      .reject { |t| @tasks.include?(t) }

    @users = if edit_users?
               User.where(id: edit_shift_event_params[:user_ids])
             else
               @occurrence.shift_event.users
             end
    @future_events_present = EventsService.find_next_occurrence(@occurrence.uid, @occurrence.starts_at + 1).present?
    @available_users = @occurrence.ownable.volunteers.reject { |u| @users.include?(u) }
  end

  def update
    if update_shift_event_params.key?(:range) && update_shift_event_params[:range] == "THISANDFUTURE"
      EventsService.update_into_future(
        @occurrence,
        shift_event_params,
        shift_frequency_params
      )
    else
      EventsService.update(
        @occurrence,
        shift_event_params,
        shift_frequency_params
      )
    end

    redirect_to updated_path, notice: "Shift was successfully updated."
  end

  def destroy
    if @occurrence.single?
      @occurrence.destroy
    elsif update_shift_event_params.key?(:range) && update_shift_event_params[:range] == "THISANDFUTURE"
      EventsService.delete_into_future(@occurrence)
    else
      EventsService.delete(@occurrence)
    end

    redirect_to organization_path(@occurrence.ownable.id), notice: "Shift was successfully destroyed."
  end

  private

  def authorize_resources
    authorize @occurrence.event if @occurrence
  end

  def updated_path
    occurrence = EventsService.find_next_occurrence(@occurrence.uid, shift_frequency_params["starts_at"])
    shift_event_occurrence_path(occurrence.id)
  end

  def shift_event_params
    params
      .require(:shift_event)
      .permit(user_ids: [], task_ids: [])
      .tap do |shift_event_params|
        shift_event_params.require(%i[user_ids task_ids])
      end
  end

  def shift_hidden_params
    params
      .permit(%i[hidden_date hidden_start hidden_end hidden_rrule])
  end

  def shift_frequency_params
    {
      "starts_at" => Time.zone.parse("#{shift_hidden_params[:hidden_date]} #{shift_hidden_params[:hidden_start]}"),
      "ends_at" => Time.zone.parse("#{shift_hidden_params[:hidden_date]} #{shift_hidden_params[:hidden_end]}"),
      "rrule" => shift_hidden_params[:hidden_rrule],
      "title" => params.fetch(:event, {}).permit(:title)[:title] || @occurrence.title
    }
  end

  def edit_shift_event_params
    params
      .fetch(:shift_event, {})
      .permit(user_ids: [], task_ids: [])
  end

  def edit_tasks?
    edit_shift_event_params.key?(:task_ids)
  end

  def edit_users?
    edit_shift_event_params.key?(:user_ids)
  end

  def update_shift_event_params
    params.permit(:range)
  end
end

app/views/shift_event_occurrences/_task_log_form.slim
.mdc-layout-grid__inner
  .mdc-layout-grid__cell
    = form_for [eventable, TaskLog.new], url: shift_event_occurrence_task_logs_path(@occurrence.id), method: "post" do |s|
      - if eventable.errors.any?
        #error_explanation
          h2 = "#{pluralize(eventable.errors.count, "error")} prohibited this organization from being saved:"
          ul
            - eventable.errors.full_messages.each do |message|
              li = message
      = s.fields_for TaskLog.new do |f|
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/select',
            id: "food_taxonomy_id",
            record: "task_log[food_taxonomy_id]",
            options: @food_taxonomies.map { |food_taxonomy| [food_taxonomy.name, food_taxonomy.id] },
            label: "Food Taxonomy",
            errors: eventable.errors[:food_taxonomy_id],
            onchange: "updateTaxonomy(event, #{task.id})"
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-6
          == render 'components/text_field', form: s, record: :weight, label: "Weight", errors: eventable.errors[:weight], onchange: "updateWeight(event, #{task.id})"
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-6
          == render 'components/text_field', form: s, record: :temperature, label: "Temp (°F)", errors: eventable.errors[:temperature], onchange: "updateTemperature(event, #{task.id})"

      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/text_area', form: s, record: :notes, label: "Notes", errors: eventable.errors[:notes]
      = s.hidden_field :task_id, value: task.id
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell
          == render 'components/submit_button', form: s, label: "Save Log", disabled: true, id: "submit-button-#{task.id}"

javascript:
  const state = [];
  const updateWeight = (e, taskId) => {
    if (state[taskId] == undefined) {state[taskId] = {}}
    if (state[taskId].validTemperature == undefined) {state[taskId].validTemperature = true}
    if (e.target.value == '' || isNaN(e.target.value) || parseInt(e.target.value) < 0) {
      state[taskId].validWeight = false;
    } else {
      state[taskId].validWeight = true;
    }
    document.getElementById(`submit-button-${taskId}`).disabled = !state[taskId].validTaxonomy || !state[taskId].validWeight || !state[taskId].validTemperature
  }
  const updateTemperature = (e, taskId) => {
    if (state[taskId] == undefined) {
      state[taskId] = {}
    }
    if (e.target.value && isNaN(e.target.value)) {
      state[taskId].validTemperature = false;
    } else {
      state[taskId].validTemperature = true;
    }
    document.getElementById(`submit-button-${taskId}`).disabled = !state[taskId].validTaxonomy || !state[taskId].validWeight || !state[taskId].validTemperature
  }
  const updateTaxonomy = (e, taskId) => {
    if (state[taskId] == undefined) {state[taskId] = {}}
    if (state[taskId].validTemperature == undefined) { state[taskId].validTemperature = true }
    if (e.target.value == '' || isNaN(e.target.value) || parseInt(e.target.value) < 0) {
      state[taskId].validTaxonomy = false;
    } else {
      state[taskId].validTaxonomy = true;
    }
    document.getElementById(`submit-button-${taskId}`).disabled = !state[taskId].validTaxonomy || !state[taskId].validWeight || !state[taskId].validTemperature
  }

app/views/shift_event_occurrences/edit.html.slim
= form_for @occurrence, url: shift_event_occurrence_path(@occurrence.id) do |f|
  .mdc-dialog id="mdc-dialog-custom" role="alertdialog" aria-labelledby="mdc-dialog-custom-label" aria-describedby="mdc-dialog-custom-description"
    .mdc-dialog__container
      .mdc-dialog__surface.mdc-layout-grid
        .mdc-dialog__header
          h3.mdc-dialog__header__title id="mdc-dialog-custom-label"
            | Save recurring event
        .mdc-dialog__body.inner-padding id="mdc-dialog-custom-description"
          .mdc-form-field.mdc-layout-grid__inner
            .mdc-radio.center-self
              input.mdc-radio__native-control type="radio" id="this-radio" name="radios"
              .mdc-radio__background
                .mdc-radio__outer-circle
                .mdc-radio__inner-circle
              .mdc-radio__ripple
            label.mdc-layout-grid__cell--span-6.center-self for="this-radio"
              h3 This event
          .mdc-form-field.mdc-layout-grid__inner
            .mdc-radio.center-self
              input.mdc-radio__native-control type="radio" id="all-radio" name="radios"
              .mdc-radio__background
                .mdc-radio__outer-circle
                .mdc-radio__inner-circle
              .mdc-radio__ripple
            label.mdc-layout-grid__cell--span-6.center-self for="all-radio"
              h3 This and following events
        br
        .mdc-dialog__footer.mdc-layout-grid__inner.inner-padding
          .mdc-layout-grid__cell.mdc-layout-grid__cell--span-6
            button.mdc-button.mdc-button--raised.mdc-dialog__button type="button" data-mdc-dialog-action="accept"
              .mdc-button__ripple
              span.mdc-button__label OK
          .mdc-layout-grid__cell.mdc-layout-grid__cell--span-6.end-text
            button.mdc-button.mdc-dialog__button type="button" data-mdc-dialog-action="close"
              span.mdc-button__label Cancel
    .mdc-dialog__scrim
    .mdc-dialog__backdrop

  .mdc-layout-grid__inner.mdc-layout-grid__space-around
    .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
      == render 'components/text_field', form: f, record: :title, label: "Name", errors: @occurrence.errors[:title]
    .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
      .mdc-layout-grid__inner.mdc-layout-grid__space-around
        #save-button.mdc-button.mdc-button--raised[onclick="openDialog('#{@occurrence.rrule}', #{@occurrence.recurrence? || @future_events_present})"] SAVE
        = f.submit "SAVE THIS EVENT",
                style: "display:none"
        = f.submit "SAVE THIS AND FOLLOWING EVENTS",
                style: "display:none",
                formaction: shift_event_occurrence_path(@occurrence.id, range: "THISANDFUTURE")

  #frequency-form-react[
    data-date="#{Time.zone.at(@occurrence.starts_at).strftime("%Y-%m-%d")}"
    data-start="#{Time.zone.at(@occurrence.starts_at).strftime('%H:%M')}"
    data-end="#{Time.zone.at(@occurrence.ends_at).strftime('%H:%M')}"
    data-rrule="#{@occurrence.rrule}"
  ]
  input#hidden-date[type="hidden" name="hidden_date"]
  input#hidden-start[type="hidden" name="hidden_start"]
  input#hidden-end[type="hidden" name="hidden_end"]
  input#hidden-rrule[type="hidden" name="hidden_rrule"]

  .mdc-layout-grid__inner
    .mdc-layout-grid__cell
      - if @occurrence.errors.any?
        #error_explanation
          h2 = "#{pluralize(@occurrence.errors.count, "error")} prohibited this shift from being saved:"
          ul
            - @occurrence.errors.full_messages.each do |message|
              li = message

  .mdc-layout-grid__inner
    .mdc-layout-grid__cell.mdc-layout-grid__cell--span-6
      .mdc-data-table.mdc-data-table__borderless.mdc-data-table__no-bottom-border
        .mdc-data-table__table-container
          table.mdc-data-table__table
            thead
              tr.mdc-data-table__header-row
                th.mdc-data-table__header-cell Tasks
            tbody.mdc-data-table__content
              - @tasks.each do |task|
                tr.mdc-data-table__row
                  td.mdc-data-table__cell= task.description
                  td.mdc-data-table__cell= check_box_tag "shift_event[task_ids][]", task.id, true

      - if params[:commit] == "ADD TASK"
        == render 'components/select',
                id: "task_id-0",
                record: "shift_event[task_ids][]",
                options: @available_tasks.map { |task| ["#{task.task_type.titleize} at #{task.site.name}", task.id] },
                label: "Task",
                errors: {}
      - else
        = text_field_tag "shift_event[task_ids][]", nil, hidden: true, id: "task_ids-0"

      div
        = f.submit "ADD TASK",
                class: "mdc-button mdc-button--raised",
                formaction: edit_shift_event_occurrence_path(@occurrence.id),
                formmethod: "PUT"

    .mdc-layout-grid__cell.mdc-layout-grid__cell--span-6
      .mdc-data-table.mdc-data-table__borderless.mdc-data-table__no-bottom-border
        .mdc-data-table__table-container
          table.mdc-data-table__table
            thead
              tr.mdc-data-table__header-row
                th.mdc-data-table__header-cell Volunteers
            tbody.mdc-data-table__content
              - @users.each do |user|
                tr.mdc-data-table__row
                  td.mdc-data-table__cell = user.full_name_or_email
                  td.mdc-data-table__cell = check_box_tag "shift_event[user_ids][]", user.id, true

      - if params[:commit] == "ADD VOLUNTEER"
        == render 'components/select',
                id: "user_id-0",
                record: "shift_event[user_ids][]",
                options: @available_users.map { |user| [user.full_name_or_email, user.id] },
                label: "Volunteer",
                errors: {}
      - else
        = text_field_tag "shift_event[user_ids][]", nil, hidden: true, id: "user_ids-0"

      div
        = f.submit "ADD VOLUNTEER",
                class: "mdc-button mdc-button--raised",
                formaction: edit_shift_event_occurrence_path(@occurrence.id),
                    formmethod: "PUT"

  hr.horizontal-rule

  .mdc-layout-grid__inner
    .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
      .horizontal-scroll-container


        .mdc-layout-grid__inner
          .mdc-layout-grid__cell.mdc-layout-grid__cell
            h3 Notes

        .mdc-layout-grid__inner.horizontal-flex-container
            - @occurrence.eventable.tasks.each do |task|
              .mdc-layout-grid__inner
                .mdc-layout-grid__cell.mdc-layout-grid__cell--span-10
                  p
                    div
                      b = task.site.name
                    - if task.site.address
                      div = task.site.address.street_one
                      - if task.site.address.street_two
                        div = task.site.address.street_two
                      div = "#{task.site.address.city}, #{task.site.address.state} #{task.site.address.zip}"
                  p[style="white-space: pre-wrap"] = task.site.instructions

        hr.horizontal-rule

        .mdc-layout-grid__inner
          .mdc-layout-grid__cell
            h3 Logs

        .mdc-layout-grid__inner.horizontal-flex-container
              - @occurrence.eventable.tasks.each do |task|
                .mdc-layout-grid__inner
                  .mdc-layout-grid__cell.mdc-layout-grid__cell--span-10
                    div
                      p = task.description

        .mdc-layout-grid__inner.horizontal-flex-container
              - @occurrence.eventable.tasks.each do |task|
                .mdc-layout-grid__inner
                  .mdc-layout-grid__cell.mdc-layout-grid__cell--span-10
                    div
                      - @occurrence.eventable.task_logs.select {|task_log| task_log.task_id == task.id}.each do |task_log|
                        p
                          div = "#{task_log.food_taxonomy&.name} #{task_log.weight} lbs"
                          - if task_log.temperature
                            div = "#{task_log.temperature}° F"
                          - if task_log.notes
                            div = task_log.notes
                          small = "Logged by #{task_log.user.full_name_or_email} at #{Time.zone.at(task_log.created_at).strftime("%F %r")}"

javascript:
  const dialogEl = document.querySelector('.mdc-dialog');
  const dialog = new mdc.dialog.MDCDialog(dialogEl);
  const radios = document.querySelectorAll('.mdc-radio');
  const thisRadio = new mdc.radio.MDCRadio(radios[0]);
  const allRadio = new mdc.radio.MDCRadio(radios[1]);

  const getSelectedRadio = (radioList) => {
    let selected = '';
    radioList.forEach((radio) => {
      if (radio.checked) selected = radio.id;
    })
    return selected;
  }
  const submitForm = () => {
    const radioFields = document.querySelectorAll('.mdc-radio input');
    const selectedRadio = getSelectedRadio(radioFields);
    if (selectedRadio === 'this-radio') {
      document.querySelector('input[value="SAVE THIS EVENT"]').click();
    } else if (selectedRadio === 'all-radio') {
      document.querySelector('input[value="SAVE THIS AND FOLLOWING EVENTS"]').click();
    }
  }

  const openDialog = (oldRrule, isRecurring) => {
    if (isRecurring) {
      if (document.querySelector('#hidden-rrule').value !== oldRrule) {
        thisRadio.disabled = true;
        thisRadio.checked = false;
        allRadio.disabled = false;
        allRadio.checked = true;
        dialog.open();
      } else {
        thisRadio.disabled = false;
        thisRadio.checked = true;
        allRadio.disabled = false;
        allRadio.checked = false;
        dialog.open();
      }
    } else {
      thisRadio.disabled = false;
      thisRadio.checked = true;
      allRadio.disabled = true;
      allRadio.checked = false;
      submitForm();
    }
  }
  dialog.listen('MDCDialog:closed', (e) => {
    if (e.detail.action !== 'accept') return;
    submitForm();
  })