config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :food_taxonomies, only: %i[index]
    resources :time_zones, only: %i[index]
    resources :shift_event_occurrences, only: %i[index show] do
      resources :task_logs, only: %i[create]
      resource :shift_event_note, path: "note", only: %i[show create]
    end
    resources :users, only: %i[show update] do
      resources :absences, only: %i[index create update destroy]
      resources :alerts, only: %i[index]
      resources :shift_event_occurrences, only: %i[index] do
        post "/pickup", to: "pickup#pickup", as: :pickup_shift
      end
      get "shift_event_occurrences/pickup", to: "pickup#index", as: :list_pickup_shifts
    end
    resources :organizations do
      resources :shifts
    end
  end

  resource :current_user, only: %i[edit update]
  resources :users, only: %i[show update]
  resources :organizations do
    resources :shifts
    resources :sites
    resources :shift_event_occurrences
    resources :users, only: %i[index show]
    resources :receipts, only: %i[new create]
    resources :csv_exporters, only: %i[create index]
  end

  resources :shift_event_occurrences, only: %i[show edit update destroy] do
    resources :task_logs, only: %i[create]
  end

  devise_for :users, path: "auth", path_names: { sign_in: "login", sign_out: "logout" }, skip: [:invitation]
  devise_scope :user do
    get "/organizations/:id/invite", to: "organization_invitations#new", as: :new_user_invitation
    post "/organizations/:id/invite", to: "organization_invitations#create", as: :create_user_invitation
    post "/organizations/:organization_id/users/:id/resend_invite", to: "users#resend_invite",
      as: :resend_user_invitation
    get "/auth/invitation/accept", to: "organization_invitations#edit", as: :accept_user_invitation
    put "/auth/invitation", to: "organization_invitations#update", as: :user_invitation
  end

  get "/rrule", to: "rrule#index"

  root to: "pages#root"

  match "*path", to: "pages#volunteer_root", via: :all
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  created_at            :datetime         not null
#  email                 :string
#  federal_tax_id        :string
#  id                    :bigint           not null, primary key
#  internal_alerts_email :string
#  name                  :string           not null
#  phone                 :string
#  tagline               :string
#  time_zone             :string           default("Etc/UTC"), not null
#  updated_at            :datetime         not null
#
class Organization < ApplicationRecord
  validates :name, presence: true
  validates :time_zone, inclusion: {
    in: ActiveSupport::TimeZone.all.map { |tz| tz.tzinfo.identifier },
    message: "Invalid time zone"
  }

  has_many :events, as: :ownable, dependent: :destroy
  has_many :sites, dependent: :destroy
  has_many :tasks, through: :sites
  has_and_belongs_to_many :users
  has_one :address, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :address, allow_destroy: true

  def volunteers
    users.volunteer
  end

  def org_admins
    users.org_admin
  end

  def shifts
    Shift.all.by_organization self
  end

  def donors
    sites.where(siteable_type: "Donor")
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  before_action :organization, only: %i[show edit update destroy]

  def index
    authorize Organization
    @organizations = policy_scope(Organization).all
  end

  def show
    authorize @organization

    @starts_at = Time.iso8601(query_params["starts_at"])
    @ends_at = @starts_at + 7.days - 1.minute
    range = @starts_at..@ends_at

    @occurrences = EventsService.all_occurrences @organization, ShiftEvent, range
  end

  def new
    authorize Organization

    @organization = Organization.new
  end

  def edit
    authorize @organization
  end

  def create
    authorize Organization

    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to @organization, notice: "Organization was successfully created."
    else
      render :new
    end
  end

  def update
    authorize @organization

    if @organization.update(organization_params)
      redirect_to edit_organization_path(@organization), notice: "Organization was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize Organization

    @organization.destroy
    redirect_to organizations_url, notice: "Organization was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def organization
    @organization = Organization.find(params[:id])
  end

  # Only allow a trusted parameter "allow list" through.
  def organization_params
    params.require(:organization).permit(
      :name,
      :tagline,
      :phone,
      :email,
      :internal_alerts_email,
      :federal_tax_id,
      :time_zone,
      address_attributes: %i[id street_one street_two city state zip _destroy]
    )
  end

  def query_params
    defaults = {
      "starts_at" => Time.current.midnight.iso8601
    }
    permitted_params = params.permit(:id, :starts_at)
    defaults
      .merge(permitted_params)
  end
end

app/views/organizations/_form.html.slim
.mdc-layout-grid__inner
  .mdc-layout-grid__cell.mdc-layout-grid__cell--span-4
    = form_for @organization do |f|
      - if @organization.errors.any?
        #error_explanation
          h2 = "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
          ul
            - @organization.errors.full_messages.each do |message|
              li = message

      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/text_field', form: f, record: :name, label: "Name", errors: @organization.errors[:name]
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/text_field', form: f, record: :tagline, label: "Tagline", errors: @organization.errors[:tagline]

      == render 'addresses/form', form: f, record_object: @organization.address

      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/text_field', form: f, record: :email, label: "Email", errors: @organization.errors[:email]
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell
          == render 'components/text_field', form: f, record: :internal_alerts_email, label: "Rootable Alerts Contact Email", errors: @organization.errors[:internal_alerts_email]
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/text_field', form: f, record: :phone, label: "Phone", errors: @organization.errors[:phone]
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/text_field', form: f, record: :federal_tax_id, label: "Federal Tax-ID", errors: @organization.errors[:federal_tax_id]
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/select',
                  form: f,
                  id: "time_zone",
                  record: :time_zone,
                  options: time_zones_with_us_zones_first.map { |tz| [tz.name, tz.tzinfo.identifier] },
                  label: "Time Zone",
                  errors: [],
                  default: @organization.time_zone || "Etc/UTC"
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
            == render 'components/submit_button', form: f, label: "Submit"
            == render 'components/link_button', label: "Cancel", url: @organization, secondary: true

app/views/organizations/edit.html.slim
.mdc-layout-grid__inner.mdc-layout-grid__space-around
  .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
    h2 Edit Organization

== render 'form'

br
hr
br
br
.mdc-layout-grid__inner.mdc-layout-grid__space-around
  .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
    = link_to "Logout", destroy_user_session_path, method: :get, class: "mdc-button mdc-button--raised"

app/views/organizations/index.html.slim
.mdc-layout-grid__inner.mdc-layout-grid__space-around
  .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
    h1 Organizations
  - if policy(Organization).new?
    .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
      == render 'components/link_button', label: "New Organization", url: new_organization_path

.mdc-data-table.mdc-data-table__borderless
  .mdc-data-table__table-container
    table.mdc-data-table__table
      thead
        tr.mdc-data-table__header-row
          th.mdc-data-table__header-cellth.mdc-data-table__header-cell Name
          th.mdc-data-table__header-cellth.mdc-data-table__header-cell Organization Admins
          th.mdc-data-table__header-cellth.mdc-data-table__header-cell Donors
          - if policy(Organization).destroy?
            th.mdc-data-table__header-cellth.mdc-data-table__header-cell

      tbody.mdc-data-table__content
        - @organizations.each do |organization|
          - href = organization_path(organization.id)
          tr.mdc-data-table__row
            == render 'components/clickable_tr', href: href
              = organization.name
            == render 'components/clickable_tr', href: href
              - organization.org_admins.each do |user|
                div
                  = user.full_name_or_email
                  = user.invitation_accepted_at.nil? ? " (Pending)" : ""
            == render 'components/clickable_tr', href: href, class: "mdc-data-table__cell--fill"
              - organization.sites.donors.each do |donor|
                div
                  = donor.name
            - if policy(organization).destroy?
              td.mdc-data-table__cell.mdc-data-table__cell--action
                == render 'components/link_button', label: 'Destroy', url: organization, data: { confirm: 'Are you sure?' }, method: :delete

app/views/organizations/new.html.slim
h2 New organization

== render 'form'

app/views/organizations/show.html.slim
.mdc-layout-grid__inner.mdc-layout-grid__space-around
  .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
    h1 = "Hello, #{@organization.name}"

.mdc-layout-grid__inner.mdc-layout-grid__space-around.tab-bar
  .mdc-layout-grid__cell.mdc-layout-grid__cell--align-middle
    == render 'components/tab/tab_bar' do
      = link_to organization_path(@organization, starts_at: (@starts_at - 7.days).iso8601),
              class: "mdc-button mdc-tab mdc-act",
              id: "previous-week",
              "aria-selected" => false,
              role: "tab",
              tabindex: 0
        i.material-icons.md-24 keyboard_arrow_left

      = link_to organization_path(@organization, starts_at: @starts_at),
              class: "mdc-button mdc-tab mdc-act",
              id: "current-week",
              "aria-selected" => true,
              role: "tab",
              tabindex: 1
        span.mdc-tab__content
          span.mdc-tab__text-label= "#{@starts_at.strftime("%b %d")}-#{@ends_at.strftime("%b %d")}"
        span.mdc-tab-indicator class="mdc-tab-indicator--active"
          span.mdc-tab-indicator__content.mdc-tab-indicator__content--underline style=""
        span.mdc-tab__ripple.mdc-ripple-upgraded

      = link_to organization_path(@organization, starts_at: (@starts_at + 7.days).iso8601),
              class: "mdc-button mdc-tab mdc-act",
              id: "next-week",
              "aria-selected" => false,
              role: "tab",
              tabindex: 2
        i.material-icons.md-24 keyboard_arrow_right
- if @occurrences.count.positive?
  .mdc-data-table__table-container
    table.mdc-data-table__table
      tbody.mdc-data-table__content
        - occurrence_groupings = @occurrences.group_by { |occur| Time.zone.at(occur.starts_at).strftime("%A %b %d") }
        - occurrence_groupings.each do |day, occurrences|
            thead
              tr
                td
                  h3 = day

            - if day == occurrence_groupings.keys.first
              tr.mdc-data-table__header-row
                th.mdc-data-table__header-cellth.mdc-data-table__header-cell Time
                th.mdc-data-table__header-cellth.mdc-data-table__header-cell Shift Name
                th.mdc-data-table__header-cellth.mdc-data-table__header-cell Tasks
                th.mdc-data-table__header-cellth.mdc-data-table__header-cell
                th.mdc-data-table__header-cellth.mdc-data-table__header-cell
                th.mdc-data-table__header-cellth.mdc-data-table__header-cell Volunteers

            - occurrences.each do |occurrence|
              - tasks = occurrence.eventable.tasks
              - flagged = occurrence.ends_at.past? ? occurrence.shift_event.missing_task_log? : occurrence.shift_event.missing_attributes?
              - href = shift_event_occurrence_path(occurrence.id)
              tr.mdc-data-table__row class=(flagged ? "mdc-data-table__row--flagged" : "")
                == render 'components/clickable_tr', href: href
                  = "#{Time.zone.at(occurrence.starts_at).strftime("%-l:%M")} - #{Time.zone.at(occurrence.ends_at).strftime("%l:%M%p")}"
                == render 'components/clickable_tr', href: href
                  = occurrence.title
                == render 'components/clickable_tr', href: href
                  = tasks.length >= 1 ? tasks[0].description : ""
                == render 'components/clickable_tr', href: href
                  = tasks.length >= 2 ? tasks[1].description : ""
                == render 'components/clickable_tr', href: href
                  = tasks.length >= 3 ? tasks[2].description : ""
                == render 'components/clickable_tr', href: href
                  - occurrence.event.shift_event.volunteers.take(2).each do |v|
                    div= v.full_name_or_email
- else
  div.empty-message No shifts to display in this time frame.