config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :food_taxonomies, only: %i[index]
    resources :time_zones, only: %i[index]
    resources :shift_event_occurrences, only: %i[index show] do
      resources :task_logs, only: %i[create]
      resource :shift_event_note, path: "note", only: %i[show create]
    end
    resources :users, only: %i[show update] do
      resources :absences, only: %i[index create update destroy]
      resources :alerts, only: %i[index]
      resources :shift_event_occurrences, only: %i[index] do
        post "/pickup", to: "pickup#pickup", as: :pickup_shift
      end
      get "shift_event_occurrences/pickup", to: "pickup#index", as: :list_pickup_shifts
    end
    resources :organizations do
      resources :shifts
    end
  end

  resource :current_user, only: %i[edit update]
  resources :users, only: %i[show update]
  resources :organizations do
    resources :shifts
    resources :sites
    resources :shift_event_occurrences
    resources :users, only: %i[index show]
    resources :receipts, only: %i[new create]
    resources :csv_exporters, only: %i[create index]
  end

  resources :shift_event_occurrences, only: %i[show edit update destroy] do
    resources :task_logs, only: %i[create]
  end

  devise_for :users, path: "auth", path_names: { sign_in: "login", sign_out: "logout" }, skip: [:invitation]
  devise_scope :user do
    get "/organizations/:id/invite", to: "organization_invitations#new", as: :new_user_invitation
    post "/organizations/:id/invite", to: "organization_invitations#create", as: :create_user_invitation
    post "/organizations/:organization_id/users/:id/resend_invite", to: "users#resend_invite",
      as: :resend_user_invitation
    get "/auth/invitation/accept", to: "organization_invitations#edit", as: :accept_user_invitation
    put "/auth/invitation", to: "organization_invitations#update", as: :user_invitation
  end

  get "/rrule", to: "rrule#index"

  root to: "pages#root"

  match "*path", to: "pages#volunteer_root", via: :all
end

app/models/receipt.rb
# == Event Occurrence
class Receipt
  attr_reader :starts_at, :ends_at, :organization, :donor, :task_logs, :created_at

  def initialize(starts_at:, ends_at:, organization_id:, donor_id:)
    @starts_at = Time.zone.parse(starts_at)
    @ends_at = Time.zone.parse(ends_at)
    @organization = Organization.find(organization_id)
    @donor = @organization.donors.find donor_id
    range = (@starts_at..@ends_at)
    @task_logs = TaskLog.where(created_at: range).joins(:task).where(tasks: { site_id: @donor.id })
    @created_at = Time.current
  end

  def total
    @task_logs.sum(&:weight)
  end

  def filename
    "#{@organization.name.gsub(/[^0-9A-z.\-]/, "_")}-#{@donor.name.gsub(/[^0-9A-z.\-]/, "_")}-receipt"
  end

  def address
    return if @organization.address.blank?

    address_street = @organization.address.street_one.to_s +
                     (@organization.address.street_two.present? ? " #{@organization.address.street_two}" : "").to_s
    "#{address_street}, #{@organization.address.city}, #{@organization.address.state} #{@organization.address.zip}"
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :authenticate_user!
  before_action :organization

  skip_before_action :verify_authenticity_token

  def create
    authorize @organization, policy_class: SitePolicy

    @receipt = Receipt.new(
      starts_at: receipt_params[:starts_at],
      ends_at: receipt_params[:ends_at],
      organization_id: params[:organization_id],
      donor_id: receipt_params[:site_id]
    )

    render template: "receipts/create", layout: false
  rescue ActiveRecord::RecordNotFound
    redirect("Donor not found.")
  rescue Date::Error
    redirect("Invalid date range.")
  end

  def new
    authorize @organization, :index?, policy_class: SitePolicy
    @donors = @organization.donors
    @selected_site_id = params[:site_id].to_i
  end

  private

  def redirect(notice)
    redirect_to new_organization_receipt_path(params[:organization_id]), notice: notice
  end

  def organization
    @organization = Organization.find(params[:organization_id])
  end

  def receipt_params
    params.permit(:site_id, :starts_at, :ends_at)
  end
end

app/views/receipts/create.html.slim
doctype 5
html
  head
    title = @receipt.filename
    style
      | body, html { font-family: 'Arial'; }
      | table, th, td { border: 1px solid black; border-collapse: collapse; }
      | td { padding: 10px; }
      | .center { text-align: center; }
      | .left { float: left; }
      | .right { float: right; }
      | .clearfix::after {
      |   content: "";
      |   clear: both;
      |   display: table;
      | }
body
  div.center
    h1 = @receipt.organization.name
    - if @receipt.organization.tagline.present?
      h3 = @receipt.organization.tagline
    - if @receipt.organization.address.present?
      p = @receipt.address
    - if @receipt.organization.email.present?
      p = @receipt.organization.email
    - if @receipt.organization.phone.present?
      p = @receipt.organization.phone
  div.clearfix
    span.left = "Receipt period: #{@receipt.starts_at.strftime("%m-%d-%Y")} to #{@receipt.ends_at.strftime("%m-%d-%Y")}"
    span.right = "Federal Tax-ID: #{@receipt.organization.federal_tax_id}"
  div.center
    p = "Receipt for: #{@receipt.donor.name}"
  table
    tr
      th Date
      th Description
      th Log #
      th Weight (lbs)
      th Temperature (Fahrenheit)
    - @receipt.task_logs.each do |log|
      tr
        td = log.created_at.strftime("%m-%d-%Y")
        td = log.food_taxonomy&.name
        td = log.id
        td = log.weight
        td = log.temperature
    tr
      td Total:
      td
      td
      td = @receipt.total
  div.center = "This receipt was generated by Rootable at #{@receipt.created_at}"

app/views/receipts/new.html.slim
h2 Generate receipts

.mdc-layout-grid__inner
  .mdc-layout-grid__cell.mdc-layout-grid__cell--span-4
    = form_for @organization, url: organization_receipts_path(@organization.id), method: 'post' do |f|
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/select',
            id: "site_id",
            record: :site_id,
            options: @donors.map { |donor| [donor.name, donor.id] },
            label: "Donor",
            errors: [],
            default: @selected_site_id
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/date_field',
                  form: f,
                  object_name: "",
                  method: "starts_at",
                  label: "Starts at",
                  errors: [],
                  default: Date.current.at_beginning_of_month.iso8601
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/date_field',
                  form: f,
                  object_name: "",
                  method: "ends_at",
                  label: "Ends at",
                  errors: [],
                  default: Date.current.at_end_of_month.iso8601
      .mdc-layout-grid__inner
        .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12
          == render 'components/submit_button', form: f, label: "Enter", target: "_blank"