config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :food_taxonomies, only: %i[index]
    resources :time_zones, only: %i[index]
    resources :shift_event_occurrences, only: %i[index show] do
      resources :task_logs, only: %i[create]
      resource :shift_event_note, path: "note", only: %i[show create]
    end
    resources :users, only: %i[show update] do
      resources :absences, only: %i[index create update destroy]
      resources :alerts, only: %i[index]
      resources :shift_event_occurrences, only: %i[index] do
        post "/pickup", to: "pickup#pickup", as: :pickup_shift
      end
      get "shift_event_occurrences/pickup", to: "pickup#index", as: :list_pickup_shifts
    end
    resources :organizations do
      resources :shifts
    end
  end

  resource :current_user, only: %i[edit update]
  resources :users, only: %i[show update]
  resources :organizations do
    resources :shifts
    resources :sites
    resources :shift_event_occurrences
    resources :users, only: %i[index show]
    resources :receipts, only: %i[new create]
    resources :csv_exporters, only: %i[create index]
  end

  resources :shift_event_occurrences, only: %i[show edit update destroy] do
    resources :task_logs, only: %i[create]
  end

  devise_for :users, path: "auth", path_names: { sign_in: "login", sign_out: "logout" }, skip: [:invitation]
  devise_scope :user do
    get "/organizations/:id/invite", to: "organization_invitations#new", as: :new_user_invitation
    post "/organizations/:id/invite", to: "organization_invitations#create", as: :create_user_invitation
    post "/organizations/:organization_id/users/:id/resend_invite", to: "users#resend_invite",
      as: :resend_user_invitation
    get "/auth/invitation/accept", to: "organization_invitations#edit", as: :accept_user_invitation
    put "/auth/invitation", to: "organization_invitations#update", as: :user_invitation
  end

  get "/rrule", to: "rrule#index"

  root to: "pages#root"

  match "*path", to: "pages#volunteer_root", via: :all
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Rootable
    link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"
    link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
    link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"
    = stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_packs_with_chunks_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

  body id=(controller.controller_name) class=(controller.action_name)
    .body-container
      - if user_signed_in?
        .siderail
          - if current_user.administrates_multiple_orgs? && !(controller?("organizations") && (action_name == "index"))
            = link_to root_path
              button#organization.mdc-icon-button.material-icons[style="color: #F3AE29"]
                | keyboard_arrow_left
          - if @organization.present? && @organization.id.present?
            = link_to organization_path(@organization)
              button#organization.mdc-icon-button.material-icons class=((controller?("organizations") && (action_name == "show")) ? "siderail__button--active md-dark" : "md-light")
                div.custom-icon.rootable-icon
            = link_to organization_users_path(@organization)
              button#users.mdc-icon-button.material-icons class=(controller?("users") ? "siderail__button--active md-dark" : "md-light")
                div.custom-icon.users-icon
            = link_to organization_sites_path(@organization)
              button#sites.mdc-icon-button.material-icons class=(controller?("sites") ? "siderail__button--active md-dark" : "md-light")
                div.custom-icon.sites-icon
            = link_to organization_shifts_path(@organization, shift_category: "recurring")
              button#shifts.mdc-icon-button.material-icons class=(controller?("shifts") ? "siderail__button--active md-dark" : "md-light")
                div.custom-icon.shifts-icon

            button#logout-menu-toggle.mdc-icon-button.material-icons.md-light[aria-label="more menu"]
              div.custom-icon.settings-icon
              #logout-menu.mdc-menu.mdc-menu-surface
                ul.mdc-list[role="menu" aria-hidden="true" aria-orientation="vertical" tabindex="-1"]
                  li.mdc-list-item[role="menuitem"]
                    span.mdc-list-item__ripple
                    span.mdc-list-item__text
                      = link_to "Edit Profile", edit_current_user_path(organization_id: @organization.id), id: 'edit-profile', :class => 'navbar-link'
                  li.mdc-list-item[role="menuitem"]
                    span.mdc-list-item__ripple
                    span.mdc-list-item__text
                      = link_to "Edit Organization", edit_organization_path(@organization), id: 'edit-org', :class => 'navbar-link'
                  li.mdc-list-item[role="menuitem"]
                    span.mdc-list-item__ripple
                    span.mdc-list-item__text
                      = link_to "Export Data", organization_csv_exporters_path(@organization), method: :get, :class => 'navbar-link'
                  li.mdc-list-item[role="menuitem"]
                    span.mdc-list-item__ripple
                    span.mdc-list-item__text
                      = link_to "Logout", destroy_user_session_path, method: :get, :class => 'navbar-link'

          - else
            button#logout-menu-toggle.mdc-icon-button.material-icons.md-light
              div.custom-icon.settings-icon
              #logout-menu.mdc-menu.mdc-menu-surface
                ul.mdc-list[role="menu" aria-hidden="true" aria-orientation="vertical" tabindex="-1"]
                  li.mdc-list-item[role="menuitem"]
                    span.mdc-list-item__ripple
                    span.mdc-list-item__text
                      = link_to "Edit Profile", edit_current_user_path, id: 'edit-profile', :class => 'navbar-link'
                  li.mdc-list-item[role="menuitem"]
                    span.mdc-list-item__ripple
                    span.mdc-list-item__text
                      = link_to "Logout", destroy_user_session_path, method: :get, :class => 'navbar-link'

      main.container role="main"
        - flash.each do |name, msg|
          .alert role="alert"
            = raw(msg)
        .mdc-layout-grid
          = yield

      footer
        section
          .mdc-layout-grid__inner
            .mdc-layout-grid__cell.mdc-layout-grid__cell--span-5.mdc-layout-grid__cell--align-middle
              = link_to "Food Rescue Alliance", "https://gitlab.com/food-rescue-alliance", class: "mdc-button"
            .mdc-layout-grid__cell.mdc-layout-grid__cell--span-7.mdc-layout-grid--align-right
              h4 = "Time Zone: #{Time.zone}"

app/views/layouts/devise.html.slim
doctype 5
html
  head
    title Rootable
    link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"
    link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
    link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"
    = stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_packs_with_chunks_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

  body id=(controller.controller_name) class=(controller.action_name)
    div
      main role="main" 
        .mdc-layout-grid
          .mdc-layout-grid__inner
            .mdc-layout-grid__cell.mdc-layout-grid__cell--span-4
            .mdc-layout-grid__cell.mdc-layout-grid__cell--span-4
              - flash.each do |name, msg|
                .alert role="alert"
                  = raw(msg)
              .mdc-layout-grid__inner style="margin-top: 4rem; justify-content: center; text-align: center;" 
                .mdc-layout-grid__cell.mdc-layout-grid__cell--span-12.mdc-layout-grid--align-center style="justify-content: center; text-align: center; margin-bottom: 3rem;"
                  img src="/rootable-stacked-dark.svg" alt="Rootable logo" width="45%" height="auto"/    
              = yield
            .mdc-layout-grid__cell.mdc-layout-grid__cell--span-4